### PR TITLE
improvements

### PR DESCRIPTION
**Pull request by SimonDanisch**
* remove id from observable
* add project.toml
* performance improvements
* small clean ups
* better stack traces & errors
* extensions to work with tasks & channels a la [generators in obervableshq](https://observablehq.com/@observablehq/introduction-to-generators)

### CODE REVIEW

**Comment by shashi** [comment]
What if I actually want an Observable of Channels? :-p

@travigd are you gonna be ok if Observable.id gets removed?

**Comment by SimonDanisch** [comment]
*bump*  :)

Btw, I've pretty much used this branch over the last half year, without running into any problems :D

**Comment by SimonDanisch** [comment]
>What if I actually want an Observable of Channels? :-p

Welp ^^ I guess it should be exotic enough to not care? And if not, you can still wrap it, I suppose

**Comment by shashi** [comment]
> I guess it should be exotic enough to not care? 

:+1:

**Pull request merged**
