### PR TITLE
Signals proposal

### PR DESCRIPTION
**Pull request by barche**
@shashi This is a very minimal implementation of the signals we discussed, just to see if what I'm doing is moving in the right direction and acceptable. Lots of stuff is of course still missing, such as the ability to disconnect signals and I also have not tried to update Observables itself yet, but normally it should be easy to make the observable contain a `Signal{1}` instead of a vector of listeners directly.

A full implementation would also support marshalling return values of the listeners, as inspired by e.g. [Boost.Signals2](http://www.boost.org/doc/libs/1_64_0/doc/html/signals2.html)

Ref https://github.com/barche/QML.jl/issues/43 and cc @timholy 

Edit: this is not meant to be merged yet, to be clear :)

### CODE REVIEW

**Comment by shashi** [comment]
Looks nice! I wonder if there's any reason we need a `value` field in Observable -- if we removed it, then Signal and Observable would be the same type! cc @JobJob for comments. Alternatively we can have a `NoValue()` special singleton type which denotes that an observable does not have a value yet. (Or use Nullable{T} for the value field)

Things we could also add:

- Instead of `Signal{N}` if we made it `Signal{Tuple{...}}` we could also enable type checking. `Signal{N}` would then be `Signal{Vararg{Any,N}}`.
- `o[] = val` would continue to call handlers with 1 argument, but `o[] = Args(val1, val2)` would call them with 2 arguments, then `emit(o, args...) = o[] = Args(args...)` would be feasible.

> A full implementation would also support marshalling return values of the listeners

Why would you want that?

**Comment by timholy** [comment]
For reference in this discussion:
```julia
julia> struct Signal{N}
           listeners::Vector
           (::Type{Signal{T}}){T}() = new{T}(Any[])
       end

julia> s = Signal{3}()
Signal{3}(Any[])

julia> sizeof(s)
8

julia> using Observables

julia> o1 = Observable(3)
Observables.Observable{Int64}(3, Any[])

julia> sizeof(o1)
16

julia> o2 = Observable(nothing)
Observables.Observable{Void}(nothing, Any[])

julia> sizeof(o2)
8
```

**Comment by barche** [comment]
I like the idea of having an observable that has its own state and therefore stores the value. It may be needed in complex systems where a listener stops listening for a while and then connects again but wants the most recent value, for example. I see an `Observable` as a value that can notify listeners for a change, so I don't see a need in this case to allow listeners with more than one argument?

The marshaling of return values is used for example in handlers of a button click: say there are multiple listeners for a button click that return true if they handled the click, it would be possible to let only the first one that handles it run, or let all of them run, depending on configuration.

**Comment by shashi** [comment]
>  It may be needed in complex systems where a listener stops listening for a while and then connects again but wants the most recent value, for example.

Seems like a completely valid reason to have it :)

> marshaling

I may be misunderstanding what you mean by marshalling... I thought you meant serialize...

**Comment by barche** [comment]
Maybe the word marshalling is not correct in this case, I mean what is described in the Boost Signals2 library:
http://www.boost.org/doc/libs/1_65_1/doc/html/signals2/tutorial.html#idp523370032

I don't really intend to implement this until I need it, though.

Regarding the status of this pull request, there are some changes I'm thinking of:

* Rename the `Signal` type here to `Event`, mainly to avoid confusion with Reactive.jl's `Signal` type, and also because if I have to describe what "signal" means in the context of this package I think "it signals that an event has happened".

* Put the Event-related stuff into a separate package

Before resubmitting an updated pull request, I'll also update the Observables branch of QML.jl to use the Julia Events package for QML events. On that matter, did you see the update on https://github.com/barche/QML.jl/issues/43 ? Is this going in the right direction for interoperability with the rest of the Julia ecosystem?

**Pull request closed without merging**
